apiVersion: v1
kind: ConfigMap
metadata:
  name: flagship-api-argocd-ops-test-proxy-config
  namespace: argocd
data:
  gogoinsight-test.syriusrobotics.com.conf: |
    server {
      listen 80;
      index index.html index.htm;
      server_name localhost;
      client_max_body_size 1G;
      location /api/argocd-ops-test{
        return 200;
      }
      location /error {
        return 404;
      }
    }
  nginx.conf: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    
    events {
      worker_connections 768;
    }
    
    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
      ssl_prefer_server_ciphers on;
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;
      gzip on;
      gzip_disable "msie6";
      include /etc/nginx/sitesavailable/*.conf;
    }    