apiVersion: v1
kind: Service
metadata:
  name: flagship-api-argocd-ops-test-proxy-svc
  namespace: argocd
spec:
  selector:
    app: flagship-api-argocd-ops-test-proxy
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8023
      targetPort: 80